version: "3.9"
services:
  db:
    image: mongo
    restart: always
    container_name: six-cities_mongodb
    env_file:
      - ../.env
    ports:
      - "27017:27017"
    volumes:
      - six-cities_data:/data/db

volumes:
  six-cities_data:
